bar:
    resource: "@BarBundle/Controller/"
    type:     annotation
    prefix:   /

foo:
    resource: "@FooBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
