# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    foo.command.foo:
        class: FooBundle\Command\FooCommand
        tags:
            - { name: console.command }
    bar.command.bar:
        class: BarBundle\Command\BarCommand
        arguments: ['foo:hello']
        tags:
            - { name: console.command }
    app.chain:
        class: FooBundle\Service\Chain

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
